openapi: 3.0.3
info:
  title: Practical 7
  description: File upload API
 
  contact:
    email: krishkevadiya6633@gmail.com
  version: 1.0.11
servers:
  - url: http://localhost:5000
tags:
  - name: Files
    description: Upload files
   
paths:
  /files:
    post:
      tags:
        - Files
      summary: Upload your file
      description: upload in form 
       consumes:
         - multipart/form-data
       parameters:
         - in: formData
           name: file_upload
           type: file
           description: Upload any file.
      responses:
        '200':
          description: Location of file in server